[package]
name = "tuber"
version = "0.1.0"
authors = ["Clément Sibille <clement.sibille@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.0"
tecs = "1.1.0"
wgpu = "0.5.0"
futures = "0.3.5"