[package]
name = "tuber"
version = "0.1.0"
authors = ["Clément Sibille <clement.sibille@protonmail.com>"]
edition = "2018"

[workspace]
members = ["examples/*"]

[features]
default = []

[[bin]]
name = "basic_application"
path = "examples/basic-application/src/main.rs"

[dependencies]
winit = "0.24.0"