[package]
name = "tuber"
version = "0.1.0"
authors = ["Clément Sibille <clement.sibille@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.0"
legion = "0.2.4"
wgpu = "0.5.0"
futures = "0.3.5"
bytemuck = "1.2.0"
async-trait = "0.1.36"
shaderc = "0.6.2"
rand = "0.7.3"
cgmath = "0.17.0"