[package]
name = "butter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
winit = "^0.27"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "^0.3.60"
wasm-bindgen = "^0.2.83"