[package]
name = "obj_parser"
version = "0.1.0"
authors = ["Tuber contributors"]
edition = "2021"

[[bin]]
path = "main.rs"
name = "obj_parser"

[dependencies]
tuber = { path = "../.." }
env_logger = "0.9.0"