[package]
name = "escape-orcs-2"
version = "0.1.0"
authors = ["Tuber contributors"]
edition = "2021"

[[bin]]
path = "main.rs"
name = "escape-orcs-2"

[dependencies]
tuber = { path = "../.." }
rand = "0.8"