name: Create diagram

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: githubocto/repo-visualizer@main
      with:
        excluded_path: ".github"
